Update the docs to reflect OperatorSource deprecation
operator-framework/operator-marketplace pull request #339
Opened 2020-09-08 13:36 UTC by ankitathomas

Switching to CatalogSource in doc to reflect OperatorSource deprecation.

2020-09-08 15:30 UTC, anik120 requested changes
Thanks for starting this @ankitathomas 

IMO since marketplace operator is now installing CatalogSources, most of the resources are olm owned, and therefore these docs should point towards relevant portions of the OLM docs. 

A doc about OperatorHub API is the only thing that's missing in terms of new addition.

2020-09-08 15:30 UTC, anik120 commented on README.md
> +If you want an `CatalogSource` to work with private registry repositories, please take a look at the [Private Repo Authentication](docs/how-to-authenticate-private-repositories.md) documentation.
This line has to be removed. We had a way to authenticate private repos using OperatorSources, but currently there's no way to authenticate using CatalogSources, unless the node itself is authenticated (which entails different steps)

2020-09-08 15:30 UTC, anik120 commented on README.md
> +Once a `CatalogSource` is created successfully you can create a [`Subscription`](https://github.com/operator-framework/operator-lifecycle-manager#discovery-catalogs-and-automated-upgrades) for your o
This should link to https://olm.operatorframework.io/docs/tasks/install-operator-with-olm/#install-your-operator

2020-09-08 15:30 UTC, anik120 commented on docs/e2e-testing.md
> +    err = helpers.CreateRuntimeObject(f, ctx, helpers.CreateOperatorSourceDefinition(name, namespace))
This is still referencing OperatorSource

2020-09-08 15:30 UTC, anik120 commented on docs/how-to-authenticate-private-repositories.md
> +If you have an registry repository that is backed by authentication, you can specify an authentication token in a Secret. To do this, create a Secret in the same namespace as your Catalog Source:
This needs to be omitted too since private repo authentication is not possible using CatalogSource

2020-09-08 15:30 UTC, anik120 commented on docs/troubleshooting.md
> -This document lists out some common failures related to the Marketplace Operator a user might encounter, along with ways to troubleshoot the failures. If you encouter a failure related to the Marketp
I have a feeling this doc needs to be ripped out mostly, and point to the olm catalogsource troubleshooting doc instead. 

What'll be helpful instead, is a doc that talks about the OperatorHub API

2024-08-13 14:58 UTC, perdasilva commented
closing due to inactivity

2024-08-13 14:58 UTC, closed without merging